PYVERSION = 2.7
PYFLAGS = -lpython$(PYVERSION)



# comment out the next line to leave out the CERN code
#CERN = -DCERN
# comment out the next line to leave out GMP expression evaluation
#GMP = -DGMP

# comment out the next line to leave out the PPL example
#WITH_PPL = -DWITH_PPL

#CC = gcc-3.4
CC = gcc
#CXX = g++-3.4
CXX = g++
CXXFLAGS = -Wall -g -I../include -fPIC -fpermissive -std=gnu++14

SWIG = swig
SWIGFLAGS = -Wall -c++ -python

#######################################################################

OBJECTS = Editor.o Buffer.o CursedEditor.o SupplyWindow.o Window.o \
		  PythonedEditor.o bindables.o
		  # py_cons_wrap_test.o py_simple_wrap_test.o
		  # Simple_wrap.o Cons_wrap.o
